---
'':
  - type: A
    value: 146.59.70.36
  - type: MX
    value:
      - exchange: mx1.mail.ovh.net.
        preference: 1
      - exchange: mx2.mail.ovh.net.
        preference: 5
      - exchange: mx3.mail.ovh.net.
        preference: 100
  - type: SPF
    value: v=spf1 include:mx.ovh.com -all
  - type: TXT
    value: v=spf1 include:mx.ovh.com -all
blog:
  type: CNAME
  value: assouman.fr.
watch:
  type: CNAME
  value: assouman.fr.