providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config
    default_ttl: 3600
    enforce_order: True
  ovh:
    class: octodns_ovh.OvhProvider
    endpoint: ovh-eu
    application_key: env/OVH_APPLICATION_KEY
    application_secret: env/OVH_APPLICATION_SECRET
    consumer_key: env/OVH_CONSUMER_KEY

zones:
  assouman.fr.:
    sources: 
      - config
    targets: 
      - ovh